'use client'
// =====================================================================
//  ArticleClient.tsx — ADSENSE REMEDIATION REWRITE (v4)
// ---------------------------------------------------------------------
//  Fixes implemented (root causes from AdSense "Low value content"):
//   1. Removed auto-generated filler verdict box (intros + buyers + endings
//      shuffled by hash). This produced text like:
//        "Mobile delivers a stable experience but doesn't lead its segment."
//      on articles that aren't even about a phone. Now the box ONLY renders
//      when there is a HUMAN-WRITTEN verdict object that passes a quality
//      gate (real content, not autogen boilerplate).
//   2. Fixed Key Highlights numbering bug — the numeric badge
//      previously rendered as "1Battery..." because the flex item
//      collapsed. Replaced with a stable <span> + proper margin.
//   3. Removed identical "Final Advice" boilerplate that appeared on
//      every single article ("The best smartphone is not decided by
//      specs alone..."). That's textbook scaled-content filler.
//   4. Removed the duplicate "Read More" trio block that pointed to
//      the same 3 pillar URLs on every article.
//   5. "Reader Reviews (0 reviews)" empty state is now collapsed — the
//      form is hidden behind a disclosure so empty articles don't
//      broadcast "no engagement" to reviewers.
//   6. Added a Pre-Launch / Speculation banner at the TOP (not the
//      bottom) for unreleased products, as recommended in audit.
//   7. Reduced article-footer emoji link bar to 4 contextual links.
//   8. Added freshness indicator + "Last updated" line under headline.
// =====================================================================
import { useState } from 'react'
import Link from 'next/link'
import type { Article } from '@/lib/store'
import ArticleCard from '@/components/ArticleCard'

interface PillarLink {
  id:    string
  path:  string
  title: string
}

interface ArticleClientProps {
  article: Article
  content: string
  similar: unknown[]
  slug:    string
  pillars?: PillarLink[]
}

// ── Brand detection map (used only for context hints, not content gen) ──
const BRAND_DETECT_MAP: [RegExp, string][] = [
  [/\bSamsung\b/i, 'Samsung'], [/\b(Apple|iPhone)\b/i, 'Apple'],
  [/\b(Xiaomi|Redmi)\b/i, 'Xiaomi'], [/\bOnePlus\b/i, 'OnePlus'],
  [/\bRealme\b/i, 'Realme'], [/\bVivo\b/i, 'Vivo'],
  [/\bOPPO\b/i, 'OPPO'], [/\biQOO\b/i, 'iQOO'],
  [/\bPoco\b/i, 'Poco'], [/\b(Motorola|Moto)\b/i, 'Motorola'],
  [/\bNothing\b/i, 'Nothing'], [/\b(Google Pixel|Pixel)\b/i, 'Google Pixel'],
  [/\bHonor\b/i, 'Honor'],
]

// ── Detect autogenerated filler verdict so we can hide it ──────────
//  These phrases appear in the hash-based pickers from the previous
//  generateUniqueVerdict() and generateStoredVerdict() functions.
//  Any verdict containing these is treated as boilerplate and NOT shown.
const FILLER_VERDICT_SIGNATURES = [
  /delivers a stable( overall)? experience/i,
  /doesn[\u2019']t lead (the|its) segment/i,
  /faces strong competition/i,
  /not the most exciting option/i,
  /doesn[\u2019']t stand out in its category/i,
  /not a category leader/i,
  /best suited for everyday users who want reliability/i,
  /makes sense for users who prefer balanced performance/i,
  /ideal for users upgrading from older devices/i,
  /works well for users who want value without complexity/i,
  /may not satisfy power users/i,
  /not be ideal for heavy gamers/i,
  /expecting flagship-level performance may feel limited/i,
  /not the best choice if you want top-tier features/i,
  /from a practical perspective/i,
  /based on overall performance/i,
  /after analyzing .{1,40} approach here/i,
  /looking at real-world usage/i,
  /this device suits users who are looking for practical performance/i,
  /a solid option for users who don[\u2019']t want to overspend/i,
  /best for users who want a simple, dependable smartphone experience/i,
  /not the right choice for users expecting flagship-level performance/i,
  /power users may find this device limiting/i,
  /not ideal if you want top-tier camera or gaming capabilities/i,
  /skip this if your priority is high-end performance/i,
  /overall, this is a practical device, but not the most exciting/i,
  /it gets the basics right, though it doesn[\u2019']t stand out/i,
  /a sensible choice for the right user, but not a category leader/i,
]

function isFillerText(s?: string): boolean {
  if (!s || typeof s !== 'string') return true
  if (s.trim().length < 40) return true // too short to be useful
  return FILLER_VERDICT_SIGNATURES.some(rx => rx.test(s))
}

function isUsefulVerdict(v?: Article['verdict']): boolean {
  if (!v) return false
  // ALL three sections must be present, long enough, and non-filler.
  return !isFillerText(v.buy) && !isFillerText(v.notBuy) && !isFillerText(v.final)
}

// ── Detect pre-launch / speculative articles for top-of-page disclosure ──
function isSpeculative(article: Article): boolean {
  const haystack = `${article.title || ''} ${article.summary || ''} ${article.content || ''}`.toLowerCase()
  // Two or more speculation markers → flag as pre-launch
  const markers = [
    'expected to launch', 'expected india price', 'expected price', 'expected pricing',
    'rumour', 'rumor', 'leaked', 'leak suggests', 'tipped to', 'tipster',
    'reportedly', 'allegedly', 'could launch', 'might launch', 'may launch',
    'pre-launch', 'pre launch', 'unconfirmed',
  ]
  let hits = 0
  for (const m of markers) {
    if (haystack.includes(m)) hits++
    if (hits >= 2) return true
  }
  return false
}

export default function ArticleClient({ article, similar, slug, content, pillars = [] }: ArticleClientProps) {
  const [reviewName, setReviewName] = useState('')
  const [reviewText, setReviewText] = useState('')
  const [reviewRating, setReviewRating] = useState(5)
  const [reviewLocation, setReviewLocation] = useState('')
  const [submitted, setSubmitted] = useState(false)
  const [showReviewForm, setShowReviewForm] = useState(false)
  const [liveArticle, setLiveArticle] = useState<Article>(article)

  const similarArticles = similar as Article[]

  // Brand resolution: detect from title if generic 'Mobile'
  const resolvedBrand: string = (() => {
    if (liveArticle.brand && liveArticle.brand !== 'Mobile') return liveArticle.brand
    for (const [rx, name] of BRAND_DETECT_MAP) {
      if (rx.test(liveArticle.title)) return name
    }
    return liveArticle.brand || 'Mobile'
  })()

  // Defensive: filter out local fallbacks, only use real proxy URLs
  const safeImages = (Array.isArray(liveArticle.images) ? liveArticle.images : [])
    .filter((img: string) => img && !img.startsWith('/phone-images/') && !img.includes('picsum'))

  const featuredImg = (() => {
    const fi = liveArticle.featuredImage || ''
    if (fi && !fi.startsWith('/phone-images/') && !fi.includes('picsum')) return fi
    if (safeImages[0]) return safeImages[0]
    return 'https://thetechbharat.com/og-image.jpg'
  })()

  const safeBullets   = Array.isArray(liveArticle.bullets)               ? liveArticle.bullets               : []
  const safeTags      = Array.isArray(liveArticle.tags)                  ? liveArticle.tags                  : []
  const safeReviews   = Array.isArray(liveArticle.reviews)               ? liveArticle.reviews               : []
  const safeQSBullets = Array.isArray(liveArticle.quickSummary?.bullets) ? liveArticle.quickSummary!.bullets : []
  const safeQSBrand   = liveArticle.quickSummary?.brand || liveArticle.brand || ''
  const safeQSDate    = liveArticle.quickSummary?.date || ''

  // ── Date formatting (no locale hydration issues) ──
  const formatDate = (iso?: string) => {
    if (!iso) return ''
    const d = new Date(iso)
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    return `${d.getUTCDate()} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`
  }
  const pubDate = formatDate(liveArticle.publishDate)
  const updDate = formatDate(liveArticle.updatedDate)
  const showUpdated = updDate && updDate !== pubDate

  const TYPE_COLORS: Record<string, string> = {
    'mobile-news': 'bg-[#1a3a5c]',
    'review':      'bg-[#d4220a]',
    'compare':     'bg-[#2a6b3c]',
  }

  // ── Quality gates ───────────────────────────────────────────────
  const showVerdictBox = isUsefulVerdict(liveArticle.verdict)
  const isPreLaunch    = isSpeculative(liveArticle)

  const handleReviewSubmit = async () => {
    if (!reviewName || !reviewText) return
    const res = await fetch(`/api/review/${slug}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: reviewName, text: reviewText, rating: reviewRating, location: reviewLocation }),
    })
    if (res.ok) {
      setSubmitted(true)
      const updated = await res.json()
      if (updated.article) setLiveArticle(updated.article)
    }
  }

  return (
    <div className="bg-paper min-h-screen">
      <div className="max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Article */}
          <article className="lg:col-span-2">
            {/* Breadcrumb */}
            <nav className="font-sans text-xs text-muted mb-4 flex items-center gap-2" aria-label="Breadcrumb">
              <Link href="/" className="hover:text-[#d4220a]">Home</Link>
              <span>/</span>
              <Link href={`/${liveArticle.type}`} className="hover:text-[#d4220a] capitalize">
                {liveArticle.type === 'review' ? 'Hands-On' : liveArticle.category}
              </Link>
              <span>/</span>
              <span className="text-ink line-clamp-1">{liveArticle.title}</span>
            </nav>

            {/* Category + Brand */}
            <div className="flex items-center gap-2 mb-3">
              <span className={`${TYPE_COLORS[liveArticle.type]} text-white font-sans text-[10px] font-bold px-2.5 py-1 uppercase tracking-widest`}>
                {liveArticle.category}
              </span>
              <span className="font-sans text-xs font-bold text-[#d4220a] uppercase">{resolvedBrand}</span>
            </div>

            {/* Title */}
            <h1 className="font-playfair text-2xl md:text-4xl font-black text-ink leading-tight mb-4">
              {liveArticle.title}
            </h1>

            {/* Meta */}
            <div className="flex flex-wrap items-center gap-3 border-b border-border pb-4 mb-5">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-full bg-[#1a3a5c] flex items-center justify-center text-white text-xs font-bold font-sans">
                  {(liveArticle.author || 'TB').split(' ').map((n: string) => n[0]).join('').slice(0,2).toUpperCase()}
                </div>
                <div>
                  <p className="font-sans text-xs font-semibold text-ink">{liveArticle.author || 'The Tech Bharat'}</p>
                  <p className="font-sans text-[10px] text-muted">The Tech Bharat</p>
                </div>
              </div>
              <span className="font-sans text-[10px] text-muted">·</span>
              <span className="font-sans text-xs text-muted" suppressHydrationWarning>
                Published {pubDate}
                {showUpdated && <> · Updated {updDate}</>}
              </span>
              <span className="font-sans text-[10px] text-muted">·</span>
              <span className="font-sans text-xs text-muted">{liveArticle.readTime} min read</span>
              {/* Share */}
              <div className="ml-auto flex items-center gap-2">
                <a
                  href={`https://wa.me/?text=${encodeURIComponent(liveArticle.title + ' ' + ('https://thetechbharat.com') + '/' + liveArticle.slug)}`}
                  target="_blank" rel="noopener noreferrer"
                  className="font-sans text-xs bg-[#25D366] text-white px-2.5 py-1 hover:opacity-80"
                >Share</a>
                <a
                  href={`https://t.me/share/url?url=${encodeURIComponent(('https://thetechbharat.com') + '/' + liveArticle.slug)}&text=${encodeURIComponent(liveArticle.title)}`}
                  target="_blank" rel="noopener noreferrer"
                  className="font-sans text-xs bg-[#2AABEE] text-white px-2.5 py-1 hover:opacity-80"
                >Telegram</a>
              </div>
            </div>

            {/* ✅ NEW: Pre-launch / Speculation disclosure (TOP, not bottom) */}
            {isPreLaunch && (
              <div className="border-l-4 border-amber-500 bg-amber-50 p-4 mb-5" role="note" aria-label="Editorial note">
                <p className="font-sans text-xs font-bold uppercase tracking-wider text-amber-800 mb-1">
                  Editorial note — Pre-launch coverage
                </p>
                <p className="font-sans text-sm text-amber-900 leading-relaxed">
                  This article covers an unreleased or unannounced product. Specifications, pricing, and availability are based on official statements or industry reports and may change. We label speculation explicitly and do not present unconfirmed claims as fact.
                </p>
              </div>
            )}

            {/* Featured Image */}
            <div className="relative mb-5 overflow-hidden" style={{ paddingBottom: '56.25%' }}>
              <img
                src={featuredImg}
                alt={liveArticle.title}
                width={1200}
                height={675}
                style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover'}}
                loading="eager"
                fetchPriority="high"
                onError={(e)=>{const t=e.target as HTMLImageElement; if(t.src!=='https://thetechbharat.com/og-image.jpg')t.src='https://thetechbharat.com/og-image.jpg'}}
              />
            </div>

            {/* Quick Summary Box */}
            {safeQSBullets.length > 0 && (
              <div className="bg-[#1a3a5c]/5 border-l-4 border-[#1a3a5c] p-4 mb-5">
                <div className="flex items-center gap-3 mb-2">
                  <span className="font-sans text-xs font-bold text-[#1a3a5c] uppercase tracking-wider">Quick Summary</span>
                  {safeQSBrand && <span className="font-sans text-xs text-muted font-semibold">{safeQSBrand}</span>}
                  {safeQSDate && <span className="font-sans text-xs text-muted ml-auto">{safeQSDate}</span>}
                </div>
                <ul className="space-y-1.5">
                  {safeQSBullets.map((b, i) => (
                    <li key={i} className="font-sans text-sm text-ink flex items-start gap-2">
                      <span className="text-[#d4220a] mt-0.5 flex-shrink-0 font-bold">✓</span>
                      <span>{b}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Introduction */}
            <p className="font-body text-lg text-[#2a2a2a] leading-relaxed mb-5">
              {liveArticle.summary}
            </p>

            {/* ✅ FIXED: Verdict box ONLY renders for human-written verdicts.
                Auto-generated filler ("Mobile delivers a stable experience...")
                is detected by isUsefulVerdict() and hidden. */}
            {showVerdictBox && liveArticle.verdict && (
              <div className="bg-[#f8f4ef] border-l-4 border-[#d4220a] p-5 mb-6">
                <h3 className="font-bold text-sm mb-2">Who should buy this?</h3>
                <p className="text-sm text-[#2a2a2a] mb-4">{liveArticle.verdict.buy}</p>

                <h3 className="font-bold text-sm mb-2">Who should NOT buy this?</h3>
                <p className="text-sm text-[#2a2a2a] mb-4">{liveArticle.verdict.notBuy}</p>

                <h3 className="font-bold text-sm mb-2">Final Verdict</h3>
                <p className="text-sm text-[#2a2a2a]">{liveArticle.verdict.final}</p>
              </div>
            )}

            {/* ✅ FIXED: Key Highlights — numbered badge no longer collapses.
                Uses inline-flex with explicit gap so "1Battery..." never happens. */}
            {safeBullets.length > 0 && (
              <div className="bg-white border border-border p-5 mb-5">
                <h3 className="font-sans text-sm font-bold text-ink uppercase tracking-wider mb-3">
                  Key Highlights
                </h3>
                <ol className="space-y-2.5 list-none p-0 m-0">
                  {safeBullets.map((b, i) => (
                    <li key={i} className="font-sans text-sm text-ink flex items-start">
                      <span
                        aria-hidden="true"
                        className="inline-flex items-center justify-center w-5 h-5 bg-[#d4220a] text-white text-[10px] font-bold rounded-full flex-shrink-0 mt-0.5"
                        style={{ marginRight: '0.625rem' }}
                      >
                        {i + 1}
                      </span>
                      <span className="flex-1">{b}</span>
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {/* Full article content */}
            <div className="article-body-full">
              {/* Inline images */}
              {safeImages[1] && (
                <div className="relative my-6 overflow-hidden" style={{ paddingBottom: '50%' }}>
                  <img src={safeImages[1]} alt={`${liveArticle.title} — detailed view`} width={800} height={450} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}} loading="lazy" onError={(e)=>{(e.target as HTMLImageElement).src="https://thetechbharat.com/og-image.jpg"}} />
                </div>
              )}

              {/* Full Content */}
              <div
                className="article-content"
                suppressHydrationWarning
                dangerouslySetInnerHTML={{ __html: content }}
              />

              {/* Mid-article image */}
              {safeImages[2] && (
                <div className="relative my-6 overflow-hidden" style={{ paddingBottom: '50%' }}>
                  <img src={safeImages[2]} alt={`${liveArticle.title} — additional image`} width={800} height={450} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}} loading="lazy" onError={(e)=>{(e.target as HTMLImageElement).src="https://thetechbharat.com/og-image.jpg"}} />
                </div>
              )}

              {/* Tags */}
              {safeTags.length > 0 && (
                <div className="flex flex-wrap gap-2 mt-6 pt-4 border-t border-border">
                  {safeTags.map(tag => (
                    <span key={tag} className="font-sans text-xs bg-gray-100 text-muted px-3 py-1 border border-border">
                      #{tag}
                    </span>
                  ))}
                </div>
              )}
            </div>

            {/* ✅ HUB LINKS: Pillar back-links — sends authority signal
                from spoke (this article) back to relevant hub pages.
                The pillar list is computed server-side based on this
                article's brand, type, and content topic, so links are
                contextual rather than identical-everywhere. */}
            <div className="mt-8 pt-6 border-t border-border">
              <p className="font-sans text-xs font-bold text-[#d4220a] uppercase tracking-wider mb-3">
                Related buyer guides
              </p>
              <div className="flex flex-wrap gap-2">
                {pillars.length > 0 ? (
                  pillars.map(p => (
                    <Link
                      key={p.id}
                      href={p.path}
                      className="font-sans text-xs text-ink border border-border bg-white px-3 py-1.5 hover:border-[#d4220a] hover:text-[#d4220a] transition-colors"
                    >
                      {p.title} →
                    </Link>
                  ))
                ) : (
                  <>
                    <Link href="/best-smartphones-india" className="font-sans text-xs text-ink border border-border bg-white px-3 py-1.5 hover:border-[#d4220a] hover:text-[#d4220a] transition-colors">
                      Best smartphones in India →
                    </Link>
                    <Link href="/smartphone-buying-guide-india" className="font-sans text-xs text-ink border border-border bg-white px-3 py-1.5 hover:border-[#d4220a] hover:text-[#d4220a] transition-colors">
                      Smartphone buying guide →
                    </Link>
                  </>
                )}
              </div>

              <p className="font-sans text-xs font-bold text-muted uppercase tracking-wider mt-5 mb-2">
                Continue browsing
              </p>
              <div className="flex flex-wrap gap-2">
                <Link href="/mobile-news" className="font-sans text-xs text-muted border border-border bg-white px-3 py-1.5 hover:border-[#d4220a] hover:text-[#d4220a] transition-colors">
                  Latest mobile news
                </Link>
                <Link href="/reviews" className="font-sans text-xs text-muted border border-border bg-white px-3 py-1.5 hover:border-[#d4220a] hover:text-[#d4220a] transition-colors">
                  Reviews
                </Link>
                <Link href="/compare" className="font-sans text-xs text-muted border border-border bg-white px-3 py-1.5 hover:border-[#d4220a] hover:text-[#d4220a] transition-colors">
                  Comparisons
                </Link>
                {resolvedBrand && resolvedBrand !== 'Mobile' && (
                  <Link
                    href={`/mobile-news?brand=${encodeURIComponent(resolvedBrand)}`}
                    className="font-sans text-xs text-muted border border-border bg-white px-3 py-1.5 hover:border-[#d4220a] hover:text-[#d4220a] transition-colors"
                  >
                    More from {resolvedBrand}
                  </Link>
                )}
              </div>
            </div>

            {/* ✅ NEW: Corrections / source transparency footer */}
            <div className="mt-6 p-4 border border-border bg-gray-50 text-xs text-muted font-sans leading-relaxed">
              <p className="font-semibold text-ink mb-1">About this article</p>
              <p>
                Written by{' '}
                <Link href="/author" className="text-[#d4220a] hover:underline">{liveArticle.author || 'Vijay Yadav'}</Link>.
                Published {pubDate}{showUpdated && <> · last updated {updDate}</>}.
                {' '}Spot an error? <Link href="/contact" className="text-[#d4220a] hover:underline">Tell us</Link> and we will correct it per our{' '}
                <Link href="/corrections-policy" className="text-[#d4220a] hover:underline">corrections policy</Link>.
              </p>
            </div>

            {/* Similar Articles */}
            {similarArticles.length > 0 && (
              <section className="mt-10 pt-6 border-t-2 border-border">
                <div className="flex items-center gap-3 mb-5">
                  <div className="w-6 h-0.5 bg-[#d4220a]" />
                  <h2 className="font-playfair text-xl font-bold">You May Also Like</h2>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {similarArticles.map(a => (
                    <ArticleCard key={a.id} article={a} variant="card" />
                  ))}
                </div>
              </section>
            )}

            {/* ✅ FIXED: Reader Reviews — empty state is collapsed.
                The "(0 reviews) — Be the first…" widget was visible on
                every article and signalled zero engagement. Now we
                only show the section if there are reviews, OR behind
                a small "Leave a review" disclosure link. */}
            {safeReviews.length > 0 && (
              <section className="mt-10 pt-6 border-t-2 border-border" aria-label="Reader reviews">
                <div className="flex items-center gap-3 mb-5">
                  <div className="w-6 h-0.5 bg-[#1a3a5c]" />
                  <h2 className="font-playfair text-xl font-bold">Reader Reviews</h2>
                  <span className="font-sans text-xs text-muted ml-2">({safeReviews.length})</span>
                </div>
                <div className="space-y-4 mb-6">
                  {safeReviews.map((review: any, i) => (
                    <div key={i} className="bg-white border border-border p-4">
                      <div className="flex items-start gap-3">
                        <div className="w-10 h-10 rounded-full bg-[#1a3a5c] text-white font-bold font-sans text-sm flex items-center justify-center flex-shrink-0">
                          {(review.name || '?').charAt(0).toUpperCase()}
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-1">
                            <span className="font-sans text-sm font-bold text-ink">{review.name}</span>
                            {review.location && (
                              <span className="font-sans text-xs text-muted">{review.location}</span>
                            )}
                            <span className="ml-auto font-sans text-xs text-muted">{review.date}</span>
                          </div>
                          <div className="flex gap-0.5 mb-2" aria-label={`${review.rating} out of 5 stars`}>
                            {Array.from({ length: 5 }).map((_, si) => (
                              <svg key={si} className={`w-3.5 h-3.5 ${si < review.rating ? 'text-amber-400' : 'text-gray-200'}`} fill="currentColor" viewBox="0 0 20 20">
                                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                              </svg>
                            ))}
                          </div>
                          <p className="font-body text-sm text-[#2a2a2a] leading-relaxed">{review.text}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* Submit a review (collapsed by default — no empty-state noise) */}
            <div className="mt-8 pt-4 border-t border-border">
              {!showReviewForm && !submitted && (
                <button
                  type="button"
                  onClick={() => setShowReviewForm(true)}
                  className="font-sans text-xs text-[#1a3a5c] font-semibold hover:underline"
                >
                  + Share your experience with this product
                </button>
              )}
              {showReviewForm && !submitted && (
                <div className="bg-white border border-border p-5">
                  <h3 className="font-sans text-sm font-bold text-ink mb-4">Share your experience</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
                    <input
                      type="text"
                      placeholder="Your name *"
                      value={reviewName}
                      onChange={e => setReviewName(e.target.value)}
                      className="font-sans text-sm border border-border px-3 py-2.5 outline-none focus:border-[#1a3a5c] w-full"
                    />
                    <input
                      type="text"
                      placeholder="City (optional)"
                      value={reviewLocation}
                      onChange={e => setReviewLocation(e.target.value)}
                      className="font-sans text-sm border border-border px-3 py-2.5 outline-none focus:border-[#1a3a5c] w-full"
                    />
                  </div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="font-sans text-xs text-muted">Rating:</span>
                    {[1, 2, 3, 4, 5].map(star => (
                      <button key={star} type="button" onClick={() => setReviewRating(star)} aria-label={`Rate ${star} stars`}>
                        <svg className={`w-5 h-5 ${star <= reviewRating ? 'text-amber-400' : 'text-gray-200'}`} fill="currentColor" viewBox="0 0 20 20">
                          <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                        </svg>
                      </button>
                    ))}
                  </div>
                  <textarea
                    placeholder="Share your thoughts... *"
                    value={reviewText}
                    onChange={e => setReviewText(e.target.value)}
                    rows={3}
                    className="font-sans text-sm border border-border px-3 py-2.5 outline-none focus:border-[#1a3a5c] w-full resize-none mb-3"
                  />
                  <button
                    type="button"
                    onClick={handleReviewSubmit}
                    className="bg-[#1a3a5c] hover:bg-[#0f2d4a] text-white font-sans font-semibold px-6 py-2.5 text-sm transition-colors"
                  >
                    Submit Review
                  </button>
                </div>
              )}
              {submitted && (
                <div className="bg-green-50 border border-green-200 p-4 text-center">
                  <p className="font-sans text-sm text-green-700 font-medium">✓ Thank you! Your review has been submitted.</p>
                </div>
              )}
            </div>
          </article>

          {/* Sidebar */}
          <aside className="lg:col-span-1 space-y-6">
            {/* ✅ STRENGTHENED: Author Bio with verifiable links */}
            <div className="bg-white border border-border p-5">
              <h3 className="font-sans text-xs font-bold uppercase tracking-widest text-muted mb-3">About the Author</h3>
              <div className="flex items-center gap-3 mb-3">
                <div className="w-12 h-12 rounded-full bg-[#d4220a] text-white font-bold font-playfair text-lg flex items-center justify-center">
                  VY
                </div>
                <div>
                  <p className="font-sans text-sm font-bold text-ink">Vijay Yadav</p>
                  <p className="font-sans text-xs text-muted">Senior Mobile Editor · New Delhi</p>
                </div>
              </div>
              <p className="font-sans text-xs text-muted leading-relaxed mb-3">
                Vijay covers the Indian smartphone market and has personally tested 300+ devices since 2014. Founder of The Tech Bharat.
              </p>
              <div className="flex items-center gap-3">
                <Link href="/author" className="font-sans text-xs font-semibold text-[#d4220a] hover:underline">
                  Full profile →
                </Link>
                <a
                  href="https://www.linkedin.com/company/the-tech-bharat/about/"
                  target="_blank"
                  rel="noopener noreferrer me"
                  className="font-sans text-xs font-semibold text-[#1a3a5c] hover:underline"
                >
                  LinkedIn
                </a>
              </div>
            </div>

            {/* Similar Articles Sidebar */}
            {similarArticles.slice(0, 4).length > 0 && (
              <div className="bg-white border border-border p-5">
                <h3 className="font-sans text-xs font-bold uppercase tracking-widest text-muted mb-4">More like this</h3>
                <div className="space-y-4">
                  {similarArticles.slice(0, 4).map(a => (
                    <ArticleCard key={a.id} article={a} variant="side" />
                  ))}
                </div>
              </div>
            )}

            {/* CTA */}
            <div className="bg-[#1a3a5c] p-5 text-white">
              <p className="font-playfair text-lg font-bold mb-2">Stay updated</p>
              <p className="font-sans text-xs opacity-80 mb-3">India-focused mobile news on your channel.</p>
              <div className="space-y-2">
                <a href="https://t.me/the_tech_bharat" target="_blank" rel="noopener noreferrer"
                  className="block bg-[#2AABEE] text-white font-sans text-xs font-semibold text-center py-2 hover:opacity-90">
                  Join Telegram →
                </a>
                <a href="https://whatsapp.com/channel/0029VbCXZfAJJhzh46IrfI2W" target="_blank" rel="noopener noreferrer"
                  className="block bg-[#25D366] text-white font-sans text-xs font-semibold text-center py-2 hover:opacity-90">
                  Join WhatsApp →
                </a>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  )
}
